export const AreasPropiedades = [
  "Baño",
  "Habitacion",
  "Lavanderia",
  "Entretenimiento",
  "Para la familia",
  "Climatizacion",
  "Seguridad",
  "Internet y oficina",
  "Cocina y comedor",
  "Sobre ubicación",
  "Exterior",
  "Estacionamiento e instalaciones",
  "Servicios",
];
export const TipoLugaresCercanos = [
  "Restaurantes",
  "Comida rapida",
  "Centros comerciales",
  "General",
  "Gym",
  "Hospitales",
  "Lavanderia",
  "Supermercados",
];
