export const ListaPaises = [
  { siglas: "AF", nombre: "Afganistán" },
  { siglas: "AL", nombre: "Albania" },
  { siglas: "DZ", nombre: "Argelia" },
  { siglas: "AD", nombre: "Andorra" },
  { siglas: "AO", nombre: "Angola" },
  { siglas: "AG", nombre: "Antigua y Barbuda" },
  { siglas: "AR", nombre: "Argentina" },
  { siglas: "AM", nombre: "Armenia" },
  { siglas: "AU", nombre: "Australia" },
  { siglas: "AT", nombre: "Austria" },
  { siglas: "AZ", nombre: "Azerbaiyán" },
  { siglas: "BS", nombre: "Bahamas" },
  { siglas: "BH", nombre: "Baréin" },
  { siglas: "BD", nombre: "Bangladés" },
  { siglas: "BB", nombre: "Barbados" },
  { siglas: "BY", nombre: "Bielorrusia" },
  { siglas: "BE", nombre: "Bélgica" },
  { siglas: "BZ", nombre: "Belice" },
  { siglas: "BJ", nombre: "Benín" },
  { siglas: "BT", nombre: "Bután" },
  { siglas: "BO", nombre: "Bolivia" },
  { siglas: "BA", nombre: "Bosnia y Herzegovina" },
  { siglas: "BW", nombre: "Botsuana" },
  { siglas: "BR", nombre: "Brasil" },
  { siglas: "BN", nombre: "Brunéi" },
  { siglas: "BG", nombre: "Bulgaria" },
  { siglas: "BF", nombre: "Burkina Faso" },
  { siglas: "BI", nombre: "Burundi" },
  { siglas: "CV", nombre: "Cabo Verde" },
  { siglas: "KH", nombre: "Camboya" },
  { siglas: "CM", nombre: "Camerún" },
  { siglas: "CA", nombre: "Canadá" },
  { siglas: "TD", nombre: "Chad" },
  { siglas: "CL", nombre: "Chile" },
  { siglas: "CN", nombre: "China" },
  { siglas: "CO", nombre: "Colombia" },
  { siglas: "KM", nombre: "Comoras" },
  { siglas: "CG", nombre: "Congo" },
  { siglas: "CR", nombre: "Costa Rica" },
  { siglas: "CI", nombre: "Costa de Marfil" },
  { siglas: "HR", nombre: "Croacia" },
  { siglas: "CU", nombre: "Cuba" },
  { siglas: "CY", nombre: "Chipre" },
  { siglas: "CZ", nombre: "Chequia" },
  { siglas: "DK", nombre: "Dinamarca" },
  { siglas: "DJ", nombre: "Yibuti" },
  { siglas: "DM", nombre: "Dominica" },
  { siglas: "DO", nombre: "República Dominicana" },
  { siglas: "EC", nombre: "Ecuador" },
  { siglas: "EG", nombre: "Egipto" },
  { siglas: "SV", nombre: "El Salvador" },
  { siglas: "GQ", nombre: "Guinea Ecuatorial" },
  { siglas: "ER", nombre: "Eritrea" },
  { siglas: "EE", nombre: "Estonia" },
  { siglas: "SZ", nombre: "Esuatini" },
  { siglas: "ET", nombre: "Etiopía" },
  { siglas: "FJ", nombre: "Fiyi" },
  { siglas: "FI", nombre: "Finlandia" },
  { siglas: "FR", nombre: "Francia" },
  { siglas: "GA", nombre: "Gabón" },
  { siglas: "GM", nombre: "Gambia" },
  { siglas: "GE", nombre: "Georgia" },
  { siglas: "DE", nombre: "Alemania" },
  { siglas: "GH", nombre: "Ghana" },
  { siglas: "GR", nombre: "Grecia" },
  { siglas: "GD", nombre: "Granada" },
  { siglas: "GT", nombre: "Guatemala" },
  { siglas: "GN", nombre: "Guinea" },
  { siglas: "GW", nombre: "Guinea-Bisáu" },
  { siglas: "GY", nombre: "Guyana" },
  { siglas: "HT", nombre: "Haití" },
  { siglas: "HN", nombre: "Honduras" },
  { siglas: "HU", nombre: "Hungría" },
  { siglas: "IS", nombre: "Islandia" },
  { siglas: "IN", nombre: "India" },
  { siglas: "ID", nombre: "Indonesia" },
  { siglas: "IR", nombre: "Irán" },
  { siglas: "IQ", nombre: "Irak" },
  { siglas: "IE", nombre: "Irlanda" },
  { siglas: "IL", nombre: "Israel" },
  { siglas: "IT", nombre: "Italia" },
  { siglas: "JM", nombre: "Jamaica" },
  { siglas: "JP", nombre: "Japón" },
  { siglas: "JO", nombre: "Jordania" },
  { siglas: "KZ", nombre: "Kazajistán" },
  { siglas: "KE", nombre: "Kenia" },
  { siglas: "KI", nombre: "Kiribati" },
  { siglas: "KP", nombre: "Corea del Norte" },
  { siglas: "KR", nombre: "Corea del Sur" },
  { siglas: "KW", nombre: "Kuwait" },
  { siglas: "KG", nombre: "Kirguistán" },
  { siglas: "LA", nombre: "Laos" },
  { siglas: "LV", nombre: "Letonia" },
  { siglas: "LB", nombre: "Líbano" },
  { siglas: "LS", nombre: "Lesoto" },
  { siglas: "LR", nombre: "Liberia" },
  { siglas: "LY", nombre: "Libia" },
  { siglas: "LI", nombre: "Liechtenstein" },
  { siglas: "LT", nombre: "Lituania" },
  { siglas: "LU", nombre: "Luxemburgo" },
  { siglas: "MG", nombre: "Madagascar" },
  { siglas: "MW", nombre: "Malaui" },
  { siglas: "MY", nombre: "Malasia" },
  { siglas: "MV", nombre: "Maldivas" },
  { siglas: "ML", nombre: "Malí" },
  { siglas: "MT", nombre: "Malta" },
  { siglas: "MH", nombre: "Islas Marshall" },
  { siglas: "MR", nombre: "Mauritania" },
  { siglas: "MU", nombre: "Mauricio" },
  { siglas: "MX", nombre: "México" },
  { siglas: "FM", nombre: "Micronesia" },
  { siglas: "MD", nombre: "Moldavia" },
  { siglas: "MC", nombre: "Mónaco" },
  { siglas: "MN", nombre: "Mongolia" },
  { siglas: "ME", nombre: "Montenegro" },
  { siglas: "MA", nombre: "Marruecos" },
  { siglas: "MZ", nombre: "Mozambique" },
  { siglas: "MM", nombre: "Birmania" },
  { siglas: "NA", nombre: "Namibia" },
  { siglas: "NR", nombre: "Nauru" },
  { siglas: "NP", nombre: "Nepal" },
  { siglas: "NL", nombre: "Países Bajos" },
  { siglas: "NZ", nombre: "Nueva Zelanda" },
  { siglas: "NI", nombre: "Nicaragua" },
  { siglas: "NE", nombre: "Níger" },
  { siglas: "NG", nombre: "Nigeria" },
  { siglas: "MK", nombre: "Macedonia" },
  { siglas: "NO", nombre: "Noruega" },
  { siglas: "OM", nombre: "Omán" },
  { siglas: "PK", nombre: "Pakistán" },
  { siglas: "PW", nombre: "Palaos" },
  { siglas: "PA", nombre: "Panamá" },
  { siglas: "PG", nombre: "Papúa Nueva Guinea" },
  { siglas: "PY", nombre: "Paraguay" },
  { siglas: "PE", nombre: "Perú" },
  { siglas: "PH", nombre: "Filipinas" },
  { siglas: "PL", nombre: "Polonia" },
  { siglas: "PT", nombre: "Portugal" },
  { siglas: "QA", nombre: "Catar" },
  { siglas: "RO", nombre: "Rumanía" },
  { siglas: "RU", nombre: "Rusia" },
  { siglas: "RW", nombre: "Ruanda" },
  { siglas: "KN", nombre: "San Cristóbal y Nieves" },
  { siglas: "LC", nombre: "Santa Lucía" },
  { siglas: "VC", nombre: "San Vicente y las Granadinas" },
  { siglas: "WS", nombre: "Samoa" },
  { siglas: "SM", nombre: "San Marino" },
  { siglas: "ST", nombre: "Santo Tomé y Príncipe" },
  { siglas: "SA", nombre: "Arabia Saudita" },
  { siglas: "SN", nombre: "Senegal" },
  { siglas: "RS", nombre: "Serbia" },
  { siglas: "SC", nombre: "Seychelles" },
  { siglas: "SL", nombre: "Sierra Leona" },
  { siglas: "SG", nombre: "Singapur" },
  { siglas: "SK", nombre: "Eslovaquia" },
  { siglas: "SI", nombre: "Eslovenia" },
  { siglas: "SB", nombre: "Islas Salomón" },
  { siglas: "SO", nombre: "Somalia" },
  { siglas: "ZA", nombre: "Sudáfrica" },
  { siglas: "SS", nombre: "Sudán del Sur" },
  { siglas: "ES", nombre: "España" },
  { siglas: "LK", nombre: "Sri Lanka" },
  { siglas: "SD", nombre: "Sudán" },
  { siglas: "SR", nombre: "Surinam" },
  { siglas: "SE", nombre: "Suecia" },
  { siglas: "CH", nombre: "Suiza" },
  { siglas: "SY", nombre: "Siria" },
  { siglas: "TW", nombre: "Taiwán" },
  { siglas: "TJ", nombre: "Tayikistán" },
  { siglas: "TZ", nombre: "Tanzania" },
  { siglas: "TH", nombre: "Tailandia" },
  { siglas: "TL", nombre: "Timor Oriental" },
  { siglas: "TG", nombre: "Togo" },
  { siglas: "TO", nombre: "Tonga" },
  { siglas: "TT", nombre: "Trinidad y Tobago" },
  { siglas: "TN", nombre: "Túnez" },
  { siglas: "TR", nombre: "Turquía" },
  { siglas: "TM", nombre: "Turkmenistán" },
  { siglas: "TV", nombre: "Tuvalu" },
  { siglas: "UG", nombre: "Uganda" },
  { siglas: "UA", nombre: "Ucrania" },
  { siglas: "AE", nombre: "Emiratos Árabes Unidos" },
  { siglas: "GB", nombre: "Reino Unido" },
  { siglas: "US", nombre: "Estados Unidos" },
  { siglas: "UY", nombre: "Uruguay" },
  { siglas: "UZ", nombre: "Uzbekistán" },
  { siglas: "VU", nombre: "Vanuatu" },
  { siglas: "VE", nombre: "Venezuela" },
  { siglas: "VN", nombre: "Vietnam" },
  { siglas: "YE", nombre: "Yemen" },
  { siglas: "ZM", nombre: "Zambia" },
  { siglas: "ZW", nombre: "Zimbabue" },

  { siglas: "PR", nombre: "Puerto Rico" },
  { siglas: "FK", nombre: "Islas Vírgenes Británicas" },
  { siglas: "GL", nombre: "Groenlandia" },
  { siglas: "HK", nombre: "Hong Kong" },
  { siglas: "MO", nombre: "Macao" },
  { siglas: "GU", nombre: "Guam" },
];
